name: Build Shattered Pixel Dungeon

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Give gradlew permission
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew :android:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: shattered-pixel-dungeon-debug
          path: android/build/outputs/apk/debug/*.apk
